app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [ 'as'=> 'index', 'uses'=> 'PagesController@index']);
Route::post('users/login', [ 'as'=> 'users.login', 'uses'=> 'UsersController@login']);
Route::get('/explore', [ 'as'=> 'explore', 'uses'=> 'PagesController@explore']);
Route::get('search', [ 'as'=> 'search', 'uses'=> 'BooksController@search']);



Route::group(['middleware' => 'guest'], function()		
	{
	Route::get('/join', [ 'as'=> 'join', 'uses'=> 'PagesController@join']);
        Route::get('/login', [ 'as'=> 'login', 'uses'=> 'PagesController@login']);
	});



Route::group(['middleware' => 'auth'], function()		
	{
	Route::get('users/logout', [ 'as'=> 'users.logout', 'uses'=> 'UsersController@logout']);
	Route::get('/account', [ 'as'=> 'account', 'uses'=> 'PagesController@account']);
	Route::post('books/store', [ 'as'=> 'storeBook', 'uses'=> 'BooksController@storeBook']);
	Route::resource('books', 'BooksController');
	});



Route::get('books/{books}',['as'=>'books.show','uses'=> 'BooksController@show']);

Route::resource('users', 'UsersController');

resources/views/account.blade.php
@extends('layout')
@section('title') Account - Booxtant @stop
@section('page-title')
Account
@stop
@section('page-content')
<div class="main-content-container container"> <div class="row"> <div class="col-md-12"> <div id="content" class="main-content-inner" role="main"> <article id="post-1707" class="post-1707 page type-page status-publish entry"> <div class="entry-content"> <div class="woocommerce"> <table class="shop_table shop_table_responsive cart" cellspacing="0"> <thead> <tr> <th class="product-name">Remove</th> <th class="product-name">Book Cover</th> <th class="product-name">Book Name</th> </tr></thead> <tbody>
                                                   @foreach ($books as $book)
                                                    <tr class="cart_item">
                                                        <td class="product-remove">
                                                            {!! Form::open(['method' => 'DELETE', 'route' => ['books.destroy', $book->id]]) !!}
                                                                {!! Form::submit('Remove', ['class' => 'btn btn-danger']) !!}
                                                            {!! Form::close() !!} 
                                                        </td>

                                                        <td class="product-thumbnail">
                                                            <a href="#"><img width="102" height="136" src="/{{$book->book_cover}}" class="attachment-shop_thumbnail size-shop_thumbnail wp-post-image" alt="book-15"></a>
                                                        </td>

                                                        <td class="product-name" data-title="Product">
                                                            <a href="#">{{$book->name}}</a> </td>
                                                    </tr>
                                                   @endforeach</tbody> </table> </div></article> </div></div></div></div>
@stop

resources/views/book-detail.blade.php
@extends('layout') 
@section('title') {{$book->name}} - Booxtant @stop
@section('page-title') {{$book->name}} @stop 
@section('search-bar')
<div class="books-search">
<div class="container">
    {!! Form::open(array('method'=>'GET','route' => 'search','autocomplete'=>'off')) !!}
    
        <div class="row">
            <div class="col-sm-9 col-md-9">
                <div class="form-group">
                {!! Form::text('search', null, array('required', 'class'=>'form-control','placeholder'=>'Search Books')) !!}
                    
                </div>
            </div>

            <div class="col-sm-3 col-md-3">
                <div class="form-group">
                {!! Form::submit('search',array('class'=>'btn btn-primary btn-block')) !!}
                </div>
            </div>

        </div>
    </form>
</div>
</div>
@stop @section('page-content')
<div id="content" class="main-content-inner" role="main">
    <div class=" product type-product status-publish has-post-thumbnail book_author-atkia product_cat-science product_tag-etnic product_tag-money product_tag-novel first instock sale shipping-taxable purchasable product-type-simple">
        <div class="images">
            <a href="#" itemprop="image" class="woocommerce-main-image zoom" title="">
                <img src="../{{$book->book_cover}}" class="attachment-shop_single size-shop_single wp-post-image" alt="" title="">
            </a>
        </div>
        <div class="summary entry-summary">
            <h1 itemprop="name" class="product_title entry-title">{{$book->name}}</h1>
            <div itemprop="description">
                <p>{{$book->description}}</p>
            </div>
            <div class="product-offer-box">
                    @if(Auth::check())
                    <a rel="nofollow" class="btn btn-danger showpdf" data-pdf="../{{$book->book_pdf}}" data-toggle="modal" data-target="#modal-fullscreen">Read Book</a>
                    @endif
                    @if(!Auth::check())
                    <a rel="nofollow" class="btn btn-danger showpdf" href="{{URL::route('join')}}">Join To Read</a>
                    @endif
            </div>
        </div>
        <div class="section-book-details clearfix">
            <div class="row">
                <div class="col-md-6">
                    <div class="book-authors">
                        <h3>Published By</h3>
                        <h4>{{$book->user->firstname}} {{$book->user->lastname}}</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal modal-fullscreen fade" id="modal-fullscreen" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                </div>
                <div class="modal-body">
                    <div id="flipbookContainer"></div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/books.blade.php
@extends('layout')
@section('title') Books - Booxtant @stop
@section('page-title')
Books
@stop
@section('search-bar')
<div class="books-search">
<div class="container">
    {!! Form::open(array('method'=>'GET','route' => 'search','autocomplete'=>'off')) !!}
    
        <div class="row">
            <div class="col-sm-9 col-md-9">
                <div class="form-group">
                {!! Form::text('search', null, array('required', 'class'=>'form-control','placeholder'=>'Search Books')) !!}
                    
                </div>
            </div>

            <div class="col-sm-3 col-md-3">
                <div class="form-group">
                {!! Form::submit('search',array('class'=>'btn btn-primary btn-block')) !!}
                </div>
            </div>

        </div>
    </form>
</div>
</div>
@stop

@section('page-content')
<div class="row">
    <div class="col-md-8">

        <div id="content" class="main-content-inner background-none" role="main">

            <ul class="products">
                @foreach ($books as $book)
                <li  class="col-md-4 post-60 product type-product status-publish has-post-thumbnail book_author-atkia product_cat-drama product_cat-love-story product_tag-money product_tag-novel product_tag-sound last instock shipping-taxable purchasable product-type-simple">
                    <div class="product-inner">
                        <a href="{{URL::to('books',array('id'=>$book->id))}}" class="woocommerce-LoopProduct-link">
                            <figure class="product-image-box"><img width="250" height="333" src="{{$book->book_cover}}" class="attachment-shop_catalog size-shop_catalog wp-post-image" alt="{{$book->name}}" title="{{$book->name}}" /></figure>
                            <div class="product-price-box clearfix">
                                <h6>{{$book->name}}</h6><span class="person-name vcard">{{$book->user->firstname}} {{$book->user->lastname}}</span>
                            </div>
                        </a>
                        <div class="woo-button-wrapper">
                            <div class="woo-button-border"><a href="{{URL::to('books',array('id'=>$book->id))}}" class="button product-button">Details</a></div>
                        </div>
                    </div>
                </li>
                @endforeach

            </ul>

            <nav class="paging-navigation">
             {{ $books->render()}}
            </nav>

        </div>

    </div>
    <div class="col-md-4">
        <aside id="sidebar" class="sidebar">
            
            <section id="woocommerce_top_rated_products-2" class="widget woocommerce widget_top_rated_products">
                <div class="widget-wrap widget-inside">
                    <h3 class="widget-title">Recently Added Books</h3>
                    <ul class="product_list_widget">
                        @foreach ($recentBooks as $recentBook)
                        <li>
                            <a href="{{URL::to('books',array('id'=>$book->id))}}" title="See Me">
                                <img width="102" height="136" src="{{$recentBook->book_cover}}" class="attachment-shop_thumbnail size-shop_thumbnail wp-post-image" alt="{{$recentBook->name}}" /> <span class="product-title">{{$recentBook->name}}</span>
                            </a>
                        </li>
                        @endforeach
                    </ul>
                </div>
            </section>
        </aside>
    </div>
</div>

@stop

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en-US">

<head>
    @include('partials.meta') 
    @include('partials.fonts')
    @include('partials.styles') 
    @include('partials.head-scripts')
</head>

<body class="page page-id-1709 page-template page-template-page_fullwidth page-template-page_fullwidth-php woocommerce-account woocommerce-page header-large ltr wpb-js-composer js-comp-ver-4.12 vc_responsive">

    <div class="site-wrap">

        <header class="section-site-header">
            <div class="site-header">
                <div class="container">
                    <div class="site-brand pull-left">
                        <a class="navbar-brand" href="{{URL::route('index')}}">
                            <div class="site-logo-text">
                            <span class="vc_icon_element-icon entypo-icon entypo-icon-book-open logo-icon"></span>
                            </div>                                                            
                            <p class="site-description">Booxtant</p>
                        </a>
                    </div>

                    <div class="site-quicknav pull-right">
                        <ul class="nav navbar-right">

                            <li class="dropdown visible-xs visible-sm">
                                <a href="#" class="dropdown-toggle" data-toggle="collapse" data-target=".navbar-collapse-top">
                                    <i class="fa fa-navicon"></i>
                                </a>
                            </li>

                            @if (Auth::check()) 
                               <li class="dropdown">
                                <a href="#" class="dropdown-toggle cart-subtotal" data-toggle="dropdown" rel="nofollow">
                                    <span class="topnav-label"><span class="amount">Welcome, {{Auth::user()->firstname}}</span></span>
                                    <i class="simple-icon-user"></i>
                                </a>
                                <ul class="dropdown-menu topnav-minicart-dropdown sm-nowrap">
                                    <li class="menu-item"><a title="My Account" href="{{URL::route('account')}}">My Books</a></li>
                                    <li class="menu-item"><a title="My Account" href="{{URL::route('books.create')}}">Add A New Book</a></li>
                                    <li class="menu-item"><a title="My Account" href="{{URL::route('users.logout')}}">Logout</a></li>
                                </ul>
                                </li>       
                                @endif
                    
                                @if (!Auth::check())
                                <li class="dropdown">
                                <a href="#" class="dropdown-toggle cart-subtotal" data-toggle="dropdown" rel="nofollow">
                                    <span class="topnav-label"><span class="amount">Welcome, Guest</span></span>
                                    <i class="simple-icon-user"></i>
                                </a>
                                <ul class="dropdown-menu topnav-minicart-dropdown sm-nowrap">
                                    <li class="menu-item"><a title="My Account" href="{{URL::route('login')}}">SIGN IN</a></li>
                                    <li class="menu-item"><a title="My Account" href="{{URL::route('join')}}">JOIN</a></li>
                                </ul>
                                </li>    
                                @endif

                        </ul>
                    </div>

                    <div class="site-menu navbar-collapse collapse navbar-collapse-top ">
                        <ul id="menu-header-menu" class="site-menu nav navbar-nav">
                            <li class="menu-item"><a title="Home" href="{{URL::route('index')}}">Home</a>
                            </li>
                            <li class="menu-item"><a title="about" href="{{URL::route('index')}}">Who We Are</a>
                            </li>
                            <li class="menu-item"><a title="Bookstore" href="{{URL::route('explore')}}">Explore Books</a></li>
                        </ul>
                    </div>

                </div>
            </div>

        </header>
        <section id="page-title" class="page-title">
            <div class="container">

                <h1>@yield('page-title')</h1>

                <ol class="breadcrumb-trail breadcrumb breadcrumbs">
                    <li><span itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a itemprop="url" class="home" href="http://demo.toko.press/bookie2/dummy">Home</a></span></li>
                    <li class="active"><span itemscope itemtype="http://data-vocabulary.org/Breadcrumb" class="active"><span itemprop="title">@yield('page-title')</span></span>
                    </li>
                </ol>
            </div>
        </section>
            @yield('search-bar')
        <div class="main-content-container container">
        	@yield('page-content')
        </div>

        <footer class="section-site-footer">

            <div class="site-footer">
                <div class="container">
                    <div class="footer-credit">
                        <p>Copyright &copy; Booxtant - 2016</p>
                    </div>
                </div>
            </div>

        </footer>

    </div>
    @include('partials.bottom-scripts')

</body>

</html>

resources/views/search.blade.php
<!DOCTYPE html>
<html lang="en-US">

<head>
    @section('title') Search Results - Bookish @stop
    @include('partials.meta') 
    @include('partials.fonts') 
    @include('partials.styles') 
    @include('partials.head-scripts') 
</head>

<body class="home page page-template page-template-page_visual_composer page-template-page_visual_composer-php header-large ltr has_slider header_absolute wpb-js-composer js-comp-ver-4.12 vc_responsive">

    <div class="site-wrap">
        <header class="section-site-header">
            <div class="site-header">
                <div class="container">
                    <h1 class="site-brand pull-left">
                    	<a class="navbar-brand" href="index.html">
                    		<div class="site-logo-text">
                            <span class="vc_icon_element-icon entypo-icon entypo-icon-book-open logo-icon"></span>
                    		</div>                                                            
                    		<p class="site-description">Booxtant</p>
                    	</a>
                  	</h1>

                    <div class="site-quicknav pull-right">
                        <ul class="nav navbar-right">

                            <li class="dropdown visible-xs visible-sm">
                                <a href="#" class="dropdown-toggle" data-toggle="collapse" data-target=".navbar-collapse-top">
                                    <i class="fa fa-navicon"></i>
                                </a>
                            </li>

                               @if (Auth::check()) 
                               <li class="dropdown">
                                <a href="#" class="dropdown-toggle cart-subtotal" data-toggle="dropdown" rel="nofollow">
                                    <span class="topnav-label"><span class="amount">Welcome, {{Auth::user()->firstname}}</span></span>
                                    <i class="simple-icon-user"></i>
                                </a>
                                <ul class="dropdown-menu topnav-minicart-dropdown sm-nowrap">
                                    <li class="menu-item"><a title="My Account" href="{{URL::route('account')}}">My Books</a></li>
                                    <li class="menu-item"><a title="My Account" href="{{URL::route('books.create')}}">Add A New Book</a></li>                      <li class="menu-item"><a title="My Account" href="{{URL::route('users.logout')}}">Logout</a></li>
                                </ul>
                                </li>       
                                @endif
                    
                                @if (!Auth::check())
                                <li class="dropdown">
                                <a href="#" class="dropdown-toggle cart-subtotal" data-toggle="dropdown" rel="nofollow">
                                    <span class="topnav-label"><span class="amount">Welcome, Guest</span></span>
                                    <i class="simple-icon-user"></i>
                                </a>
                                <ul class="dropdown-menu topnav-minicart-dropdown sm-nowrap">
                                    <li class="menu-item"><a title="My Account" href="{{URL::route('login')}}">SIGN IN</a></li>
                                    <li class="menu-item"><a title="My Account" href="{{URL::route('join')}}">JOIN</a></li>
                                </ul>
                                </li>    
                                @endif                            
                        </ul>
                    </div>

                    <div class="site-menu navbar-collapse collapse navbar-collapse-top ">
                        <ul id="menu-header-menu" class="site-menu nav navbar-nav">
                            <li class="menu-item"><a title="Home" href="{{URL::route('index')}}">Home</a>
                            </li>
                            <li class="menu-item"><a title="about" href="{{URL::route('index')}}">Who We Are</a>
                            </li>
                            <li class="menu-item"><a title="Bookstore" href="{{URL::route('explore')}}">Explore Books</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </header>
        <div class="toko-slider-wrap">
            <div class="toko-slides toko-slider-active owl-carousel owl-theme owl-loaded">
                <div class="toko-slide" style="background-image:url(images/slider-01.jpg);background-size:cover;background-position:center right;background-repeat:no-repeat;">
                    <div class="toko-slide-inner">
                        <div class="toko-slide-detail">
                            <p class="toko-slide-desc">If there's a book that you want to read, but it hasn't been written yet, then you must write it.</p>
                            <h4 class="toko-slide-title">Let's Get Started</h4><a class="toko-slide-button" href="{{URL::route('join')}}">Learn More</a></div>
                    </div>
                </div>
                <div class="toko-slide" style="background-image:url(images/slider-02.jpg);background-size:cover;background-position:center right;background-repeat:no-repeat;">
                    <div class="toko-slide-inner">
                        <div class="toko-slide-detail">
                            <p class="toko-slide-desc">If you only read the books that everyone else is reading, you can only think what everyone else is thinking</p>
                            <h4 class="toko-slide-title">Explore Our Collection</h4><a class="toko-slide-button" href="{{URL::route('explore')}}">Explore</a></div>
                    </div>
                </div>

            </div>
        </div>
        <div class="main-content">

            <div class="main-content-container container">
                <div id="content" class="main-content-inner" role="main">

                    <article id="post-701" class="post-701 page type-page status-publish entry">

                        <div class="entry-content">

                            <div data-vc-full-width="true" data-vc-full-width-init="false" data-vc-stretch-content="true" class="vc_row wpb_row vc_row-fluid vc_row-no-padding">
                                <div class="wpb_column vc_column_container vc_col-sm-12">
                                    <div class="vc_column-inner ">
                                        <div class="wpb_wrapper">
                                            <div class="books-search">
                                                <div class="container">
                                                    {!! Form::open(array('method'=>'GET','route' => 'search','autocomplete'=>'off')) !!}
                                                    
                                                        <div class="row">
                                                            <div class="col-sm-9 col-md-9">
                                                                <div class="form-group">
                                                                {!! Form::text('search', null, array('required', 'class'=>'form-control','placeholder'=>'Search Books')) !!}
                                                                    
                                                                </div>
                                                            </div>

                                                            <div class="col-sm-3 col-md-3">
                                                                <div class="form-group">
                                                                {!! Form::submit('search',array('class'=>'btn btn-primary btn-block')) !!}
                                                                </div>
                                                            </div>

                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="vc_row-full-width vc_clearfix"></div>
                            <div data-vc-full-width="true" data-vc-full-width-init="false" class="vc_row wpb_row vc_row-fluid vc_custom_1453085217674 vc_row-has-fill">
                                <div class="wpb_column vc_column_container vc_col-sm-12">
                                    <div class="vc_column-inner ">
                                        <div class="wpb_wrapper">

                                            <div class="toko-divider text-center line-no icon-no">

                                                <div class="divider-inner" style="background-color: #edf3f4">

                                                    <h3 class="toko-section-title">Your Search Results</h3>

                                                </div>
                                            </div>

                                            <div class="toko-woocommerce woocommerce columns-4 toko-no-carousel clearfix">

                                                <ul class="products " id="toko-carousel-263">

                                                @foreach ($results as $result)
                                                    <li class="product">
                                                        <div class="product-inner">
                                                            <a href="{{URL::to('books',array('id'=>$result->id))}}" class="woocommerce-LoopProduct-link">
                                                                <figure class="product-image-box">
                                                                    <span class="onsale">Recently Added</span>
                                                                    <img width="250" height="333" src="{{$result->book_cover}}" class="attachment-shop_catalog size-shop_catalog wp-post-image" alt="{{$result->name}}" title="{{$result->name}}"></figure>
                                                                <div class="product-price-box clearfix">
                                                                    <h3>{{$result->name}}</h3><span class="person-name vcard">Published By : </span>
                                                                    </del> <ins><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol"></span>{{$result->user->firstname}} {{$result->user->lastname}}</span></ins></span>
                                                                </div>
                                                            </a>
                                                            <div class="woo-button-wrapper">
                                                                <div class="woo-button-border"><a href="{{URL::to('books',array('id'=>$result->id))}}" class="button product-button">Detail</a><!--
                                                                -->@if(Auth::check())<!--
                                                                --><a rel="nofollow" data-pdf="{{$result->book_pdf}}"  class="showpdf button product_type_simple add_to_cart_button ajax_add_to_cart " data-toggle="modal" data-target="#modal-fullscreen">Read</a>
                                                                @endif<!--
                                                                -->@if(!Auth::check())<!--
                                                                --><a href="{{URL::route('join')}}" rel="nofollow" class="showpdf button product_type_simple add_to_cart_button ajax_add_to_cart ">Join To Read</a>
                                                                @endif
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </li>
                                                
                                                @endforeach
                                                </ul>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="vc_row-full-width vc_clearfix"></div>
                        </div>

                    </article>

                </div>
            </div>

        </div>

        <footer class="section-site-footer">

            <div class="site-footer">
                <div class="container">
                    <div class="footer-credit">
                        <p>Copyright &copy; Booxtant - 2016</p>
                    </div>

                </div>
            </div>

        </footer>

    </div>
    <div class="modal modal-fullscreen fade" id="modal-fullscreen" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      </div>
      <div class="modal-body">
       <div id="flipbookContainer"></div>
      </div>
    </div>
  </div>
</div>
    {{-- <div id="flipbookContainer"></div> --}}


    @include('partials.bottom-scripts')
</body>

</html>